/**
 * ════════════════════════════════════════════════════════════════════════
 * FORGE — Live Preview Panel
 *
 * Enhanced full-screen preview of the generated app with:
 *   • Sandboxed iframe rendering
 *   • Responsive device frames (desktop, tablet, mobile)
 *   • Export as HTML
 *   • Screenshot-like overlay
 *   • Zoom controls
 * ════════════════════════════════════════════════════════════════════════
 */

import { useState, useRef, useMemo } from "react";
import {
  Monitor,
  Tablet,
  Smartphone,
  ZoomIn,
  ZoomOut,
  Maximize2,
  Download,
  Code2,
  RotateCcw,
  Copy,
  Check,
} from "lucide-react";
import { useForge } from "../lib/forgeState";
import BlueprintRenderer from "./BlueprintRenderer";

/* ── Device presets ────────────────────────────────────────────────── */

const devices: { id: string; label: string; icon: React.ReactNode; width: string; maxWidth: string }[] = [
  { id: "desktop", label: "Desktop", icon: <Monitor size={14} />, width: "100%", maxWidth: "100%" },
  { id: "tablet", label: "Tablet", icon: <Tablet size={14} />, width: "768px", maxWidth: "768px" },
  { id: "mobile", label: "Mobile", icon: <Smartphone size={14} />, width: "375px", maxWidth: "375px" },
];

type DeviceId = string;

/* ── HTML Export generator ─────────────────────────────────────────── */

function generateExportHTML(blueprint: ReturnType<typeof useForge>["activeBlueprint"]): string {
  if (!blueprint) return "";

  const sectionsHtml = blueprint.sections
    .map((section) => {
      const comps = section.components
        .map((c) => `    <div class="component" data-component="${c.componentName}">\n      <h4>${c.componentName}</h4>\n      <pre>${JSON.stringify(c.props, null, 2)}</pre>\n    </div>`)
        .join("\n");
      return `  <section id="${section.id}">\n${section.heading ? `    <h2>${section.heading}</h2>\n` : ""}${comps}\n  </section>`;
    })
    .join("\n\n");

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${blueprint.appType} — Built with Forge</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: system-ui, sans-serif; background: #030712; color: #f9fafb; }
    section { padding: 2rem; border-bottom: 1px solid #1f2937; }
    h2 { font-size: 1.5rem; margin-bottom: 1rem; }
    .component { background: #111827; border: 1px solid #374151; border-radius: 0.75rem; padding: 1rem; margin-bottom: 1rem; }
    .component h4 { color: #818cf8; font-size: 0.875rem; margin-bottom: 0.5rem; }
    .component pre { font-size: 0.75rem; color: #9ca3af; white-space: pre-wrap; }
  </style>
</head>
<body>
  <header style="padding:1rem 2rem;border-bottom:1px solid #1f2937">
    <h1 style="font-size:1.25rem">${blueprint.appType} <span style="color:#6366f1;font-size:0.75rem">Built with Forge</span></h1>
  </header>

${sectionsHtml}

  <footer style="padding:1rem 2rem;text-align:center;color:#6b7280;font-size:0.75rem">
    Generated by Forge AI Product Builder
  </footer>
</body>
</html>`;
}

/* ── Main component ────────────────────────────────────────────────── */

export default function LivePreview() {
  const { activeBlueprint, history, activeIndex, dispatch } = useForge();
  const [device, setDevice] = useState<DeviceId>("desktop");
  const [zoom, setZoom] = useState(100);
  const [showCode, setShowCode] = useState(false);
  const [copied, setCopied] = useState(false);
  const previewRef = useRef<HTMLDivElement>(null);

  const currentDevice = devices.find((d) => d.id === device)!;
  const revision = activeIndex >= 0 ? history[activeIndex].revision : 0;

  const exportHtml = useMemo(
    () => generateExportHTML(activeBlueprint),
    [activeBlueprint],
  );

  function handleDownloadHTML() {
    if (!exportHtml) return;
    const blob = new Blob([exportHtml], { type: "text/html" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `forge-${activeBlueprint?.appType || "app"}-v${revision}.html`;
    a.click();
    URL.revokeObjectURL(url);
  }

  function handleCopyBlueprint() {
    if (!activeBlueprint) return;
    navigator.clipboard.writeText(JSON.stringify(activeBlueprint, null, 2));
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }

  if (!activeBlueprint) {
    return (
      <div className="h-full flex flex-col items-center justify-center text-center px-8 bg-gray-950/50">
        <div className="w-20 h-20 rounded-2xl bg-gray-800/50 border border-gray-700/50 flex items-center justify-center mb-4">
          <Monitor size={32} className="text-gray-600" />
        </div>
        <h3 className="text-sm font-semibold text-gray-400 mb-2">No preview available</h3>
        <p className="text-xs text-gray-600 max-w-sm mb-4">
          Describe a product idea in the Build tab to generate your first app,
          then come here to preview it in different device sizes.
        </p>
        <button
          onClick={() => dispatch({ type: "SET_TAB", tab: "build" })}
          className="px-4 py-2 text-xs rounded-lg bg-indigo-500/20 text-indigo-300 border border-indigo-500/30 hover:bg-indigo-500/30 transition-colors"
        >
          Go to Build
        </button>
      </div>
    );
  }

  return (
    <div className="h-full flex flex-col overflow-hidden bg-gray-950/50">
      {/* ── Toolbar ─────────────────────────────────────────────────── */}
      <div className="px-4 py-2.5 border-b border-gray-700/50 bg-gray-900/80 shrink-0">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-3">
            <span className="text-xs font-semibold text-gray-400">
              {activeBlueprint.appType}
            </span>
            <span className="text-[10px] px-2 py-0.5 bg-indigo-500/20 text-indigo-300 rounded-full">
              v{revision}
            </span>
            <span className="text-[10px] text-gray-600">
              {activeBlueprint.sections.length} sections
            </span>
          </div>

          <div className="flex items-center gap-1">
            {/* Device toggles */}
            {devices.map((d) => (
              <button
                key={d.id}
                onClick={() => setDevice(d.id)}
                className={`p-1.5 rounded-md transition-colors ${
                  device === d.id ? "bg-gray-700 text-white" : "text-gray-500 hover:text-gray-300"
                }`}
                title={d.label}
              >
                {d.icon}
              </button>
            ))}

            <div className="w-px h-4 bg-gray-700 mx-1.5" />

            {/* Zoom */}
            <button
              onClick={() => setZoom((z) => Math.max(50, z - 10))}
              className="p-1.5 rounded-md text-gray-500 hover:text-gray-300"
              title="Zoom out"
            >
              <ZoomOut size={14} />
            </button>
            <span className="text-[10px] text-gray-500 w-8 text-center font-mono">{zoom}%</span>
            <button
              onClick={() => setZoom((z) => Math.min(150, z + 10))}
              className="p-1.5 rounded-md text-gray-500 hover:text-gray-300"
              title="Zoom in"
            >
              <ZoomIn size={14} />
            </button>
            <button
              onClick={() => setZoom(100)}
              className="p-1.5 rounded-md text-gray-500 hover:text-gray-300"
              title="Reset zoom"
            >
              <RotateCcw size={14} />
            </button>

            <div className="w-px h-4 bg-gray-700 mx-1.5" />

            {/* Actions */}
            <button
              onClick={() => setShowCode(!showCode)}
              className={`flex items-center gap-1 px-2 py-1 rounded-md text-xs transition-colors ${
                showCode
                  ? "bg-emerald-500/20 text-emerald-300"
                  : "text-gray-400 hover:text-gray-200 hover:bg-gray-800"
              }`}
            >
              <Code2 size={12} />
              {showCode ? "Preview" : "Code"}
            </button>
            <button
              onClick={handleCopyBlueprint}
              className="flex items-center gap-1 px-2 py-1 rounded-md text-xs text-gray-400 hover:text-gray-200 hover:bg-gray-800 transition-colors"
              title="Copy blueprint JSON"
            >
              {copied ? <Check size={12} className="text-emerald-400" /> : <Copy size={12} />}
            </button>
            <button
              onClick={handleDownloadHTML}
              className="flex items-center gap-1 px-2 py-1 rounded-md text-xs text-gray-400 hover:text-gray-200 hover:bg-gray-800 transition-colors"
              title="Download HTML"
            >
              <Download size={12} />
            </button>
          </div>
        </div>
      </div>

      {/* ── Revision breadcrumbs ────────────────────────────────────── */}
      {history.length > 1 && (
        <div className="px-4 py-1.5 border-b border-gray-800/50 flex items-center gap-1 overflow-x-auto shrink-0">
          <span className="text-[10px] text-gray-600 mr-1 shrink-0">Rev:</span>
          {history.map((snap, i) => (
            <button
              key={i}
              onClick={() => dispatch({ type: "SET_ACTIVE_INDEX", index: i })}
              className={`px-2 py-0.5 text-[10px] rounded-full shrink-0 transition-colors ${
                i === activeIndex
                  ? "bg-indigo-500/30 text-indigo-300"
                  : "bg-gray-800 text-gray-500 hover:text-gray-300"
              }`}
            >
              v{snap.revision}
            </button>
          ))}
        </div>
      )}

      {/* ── Preview area ────────────────────────────────────────────── */}
      <div className="flex-1 overflow-auto p-6 flex justify-center">
        {showCode ? (
          <div className="w-full max-w-4xl">
            <div className="rounded-xl bg-gray-900 border border-gray-800 overflow-hidden">
              <div className="flex items-center justify-between px-4 py-2 bg-gray-800/50 border-b border-gray-800">
                <span className="text-xs text-gray-400 font-mono">blueprint.json</span>
                <button
                  onClick={handleCopyBlueprint}
                  className="text-[10px] text-gray-500 hover:text-white flex items-center gap-1"
                >
                  {copied ? <Check size={10} /> : <Copy size={10} />}
                  {copied ? "Copied!" : "Copy"}
                </button>
              </div>
              <pre className="p-4 text-xs text-emerald-300 font-mono overflow-auto max-h-[70vh] leading-relaxed">
                {JSON.stringify(activeBlueprint, null, 2)}
              </pre>
            </div>
          </div>
        ) : (
          <div
            ref={previewRef}
            className="transition-all duration-300"
            style={{
              width: currentDevice.width,
              maxWidth: currentDevice.maxWidth,
              transform: `scale(${zoom / 100})`,
              transformOrigin: "top center",
            }}
          >
            {/* Device frame */}
            <div
              className={`bg-gray-900 rounded-2xl border border-gray-700/50 overflow-hidden shadow-2xl ${
                device !== "desktop" ? "shadow-indigo-500/5" : ""
              }`}
            >
              {/* Browser chrome */}
              <div className="flex items-center gap-2 px-3 py-2 bg-gray-800/80 border-b border-gray-700/50">
                <div className="flex gap-1.5">
                  <div className="w-2.5 h-2.5 rounded-full bg-red-500/60" />
                  <div className="w-2.5 h-2.5 rounded-full bg-yellow-500/60" />
                  <div className="w-2.5 h-2.5 rounded-full bg-green-500/60" />
                </div>
                <div className="flex-1 mx-4">
                  <div className="bg-gray-900/80 rounded-md px-3 py-1 text-[10px] text-gray-500 text-center truncate">
                    forge-preview://{activeBlueprint.appType}.app
                  </div>
                </div>
              </div>

              {/* App content */}
              <div className="overflow-y-auto" style={{ maxHeight: device === "mobile" ? "667px" : device === "tablet" ? "1024px" : "none" }}>
                <div className="p-4">
                  <BlueprintRenderer blueprint={activeBlueprint} />
                </div>
              </div>
            </div>

            {/* Device info */}
            <p className="text-center text-[10px] text-gray-600 mt-3">
              {currentDevice.label} · {currentDevice.maxWidth === "100%" ? "Full width" : currentDevice.maxWidth}
              {zoom !== 100 && ` · ${zoom}%`}
            </p>
          </div>
        )}
      </div>
    </div>
  );
}
